#!/usr/bin/env python3
"""Replay the Honold note rule against a Soll-Ist-Vergleich workbook.

Local evidence tool (the workbook is customer data and is gitignored). It uses
the same plaintext tariff as the browser loader, generated by
scripts/honold/build_tariff.py, and prints any row where the rule disagrees
with the workbook's Anmerkung column.

    python scripts/honold/validate_rule.py [workbook.xlsx] [tariff.xlsx]
"""
import sys
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts" / "honold"))
import build_tariff  # noqa: E402

OLD_NOTE = "Honold berechnet die Kosten nach dem bisherigen Tarif"
DIFF_NOTE = "Differenz aufgrund abweichender Gewichte"
RATE_TOL = 0.005
# The workbook's Anmerkung column is no longer the oracle. The domain owner
# confirmed rows 5, 7, 18, 32, 57, 58, 98, 104, 107, 121 and 125 are labelled
# "Differenz" but should read "bisherigen Tarif", and row 90 is a real
# rule-vs-workbook disagreement. Pinned so the 112/124 evidence cannot shift
# silently.
KNOWN_OUTLIERS = {5, 7, 18, 32, 57, 58, 90, 98, 104, 107, 121, 125}


def num(v):
    if v in (None, ""):
        return None
    try:
        return float(str(v).replace(",", "."))
    except ValueError:
        return None


def tier_idx(tiers, kg):
    if kg is None or kg <= 0:
        return None
    for i, t in enumerate(tiers):
        if kg <= t:
            return i
    return len(tiers) - 1


def fr_tiers(tariff, land, fr):
    """Bracket indices in the country's column(s) whose rate equals fr."""
    if fr is None or not land or abs(fr) <= RATE_TOL:
        return []
    out = []
    for z in tariff["codes"].get(str(land).upper(), []):
        for i, v in enumerate(tariff["zones"].get(z, [])):
            if v is not None and abs(float(v) - fr) <= RATE_TOL and i not in out:
                out.append(i)
    return out


def main():
    wb_path = sys.argv[1] if len(sys.argv) > 1 else r"D:\TESTER\Honold\20379045 Soll-Ist-Vergleich.xlsx"
    xlsx_path = sys.argv[2] if len(sys.argv) > 2 else r"D:\TESTER\Honold OLD Tariff.xlsx"
    tariff = build_tariff.build(xlsx_path)
    ws = openpyxl.load_workbook(wb_path, data_only=True).active
    total = wrong = 0
    mismatches = []
    for r in range(4, ws.max_row + 1):
        truth = ws.cell(r, 63).value
        if not truth:
            continue
        total += 1
        stat = num(ws.cell(r, 34).value)
        land = ws.cell(r, 15).value
        fr = num(ws.cell(r, 45).value)
        vkg = num(ws.cell(r, 31).value)
        if stat != 10:
            # The engine returns null and writes nothing on a gate skip.
            continue
        elif fr is None or abs(fr) <= RATE_TOL:
            # Blank / 0 FR never names a bracket: same branch as the engine.
            pred = DIFF_NOTE
        else:
            i_ae = tier_idx(tariff["tiers"], vkg)
            pred = OLD_NOTE if (i_ae is not None and i_ae in fr_tiers(tariff, land, fr)) else DIFF_NOTE
        if pred != truth:
            wrong += 1
            mismatches.append(r)
            print("row %d: truth=%r pred=%r (land=%s fr=%s vkg=%s)"
                  % (r, truth, pred, land, fr, vkg))
    unexpected = sorted(set(mismatches) - KNOWN_OUTLIERS)
    print("%d rows, %d mismatches (pinned outliers %s%s)"
          % (total, wrong, sorted(KNOWN_OUTLIERS),
             ", unexpected %s" % unexpected if unexpected else ""))
    if set(mismatches) != KNOWN_OUTLIERS:
        print("FAIL: mismatches are not exactly the pinned outliers")
        sys.exit(1)


if __name__ == "__main__":
    main()
